#!/bin/sh
set -e

case "$1" in
  configure|abort-upgrade|abort-remove|abort-deconfigure)
    if [ -d /run/systemd/system ]; then
      systemctl daemon-reload >/dev/null 2>&1 || true
      systemctl enable release-test.service >/dev/null 2>&1 || true
      systemctl start release-test.service >/dev/null 2>&1 || true
    fi
    ;;
esac

exit 0
